### ISSUE TITLE
AttributeError: module 'tensorboard.plugins.pr_curve.summary' has no attribute 'pb'

### ISSUE THREAD

**Issue by NidhiSingh963** [aqeelanwar/SocialDistancingAI#3]

**Comment by aqeelanwar** [comment]
Yout provided information not enough to debug the issue.

**Comment by zainozzaini** [comment]
@NidhiSingh963 - I got that error too on fresh install. Lastly manage to run the code by uninstall tensorflow-tensorboard. Thanks to this conversation - [https://github.com/tensorflow/tensorboard/issues/1862#issuecomment-521876133](https://github.com/tensorflow/tensorboard/issues/1862#issuecomment-521876133)
