### ISSUE TITLE
Doubt regarding block diagram

### ISSUE THREAD

**Issue by csetarun** [aqeelanwar/SocialDistancingAI#4]
Even though they are completed, why **Project pedestrian location on bird's eye view** and **Find distance between pedestrians**  are separated without any dotted line. What does that dotted line signify?

![image](https://user-images.githubusercontent.com/7066620/81243986-d7b3c680-902e-11ea-9a78-bbeef6872381.png)

**Comment by aqeelanwar** [comment]
The dotted lines have no significance other than that the block grouped by dotted lines are similar in nature.
