### ISSUE TITLE
Function issue plot_lines_between_nodes

### ISSUE THREAD

**Issue by abc1110** [aqeelanwar/SocialDistancingAI#6]
In the function `plot_lines_between_nodes()` the for loop is made to run through `range(len(dd[0]))/2)` due to which all pairs of nodes are not getting taken into account. 

Consider the following example: 

```
dist = np.array([[0,173.66634677,194.6715182,1173.33413826],
                 [173.66634677,0,24.35159132, 1077.55324694],
                 [194.6715182, 24.35159132, 0, 1056.10037402],
                 [1173.33413826, 1077.55324694, 1056.10037402, 0]])

thresh =  350

dd = np.where(dist < thresh *  6 / 10)

close_p = []

for i in range(int(np.ceil(len(dd[0]) / 2))):
    if dd[0][i] != dd[1][i]:
        point1 = dd[0][i]
        point2 = dd[1][i]

        close_p.append([point1, point2])
```

The resultant points in `close_p` are ` [[0, 1], [0, 2], [1, 0]]`
and it misses out on pairs `[[1,2], [2,1]]`

**Comment by aqeelanwar** [comment]
Thanks for pointing out. I wanted to include the pair of points once in the list irrespective of the order. The following modification should fix it.
`import numpy as np
dist = np.array([[0,173.66634677,194.6715182,1173.33413826],
                 [173.66634677,0,24.35159132, 1077.55324694],
                 [194.6715182, 24.35159132, 0, 1056.10037402],
                 [1173.33413826, 1077.55324694, 1056.10037402, 0]])

thresh =  350

dd = np.where(dist < thresh *  6 / 10)
print(dd)
close_p = []

for i in range(int(np.ceil(len(dd[0])))):
    if dd[0][i] != dd[1][i]:
        point1 = dd[0][i]
        point2 = dd[1][i]
        
        if [point2, point1] not in close_p and [point1, point2] not in close_p:
            close_p.append([point1, point2])
print(close_p)`

**Comment by lchunleo** [comment]
can you explain the design for the checking of distancing violations? thank you
